### ISSUE TITLE
[ISSUE] bot not starting

### ISSUE THREAD

**Issue by Rocky-pup** [pieckenst/openbot#139]
Traceback (most recent call last):
  File "C:\Users\ojoman\Desktop\src\main.py", line 137, in <module>
    bot = Helia()
  File "C:\Users\ojoman\Desktop\src\main.py", line 70, in __init__
    look.launch_time = datetime.datetime.utcnow()
NameError: name 'look' is not defined
Loading modules...
Default locale is en_EN

this on every start
what i can do?
![image](https://user-images.githubusercontent.com/83218418/124600199-247f7100-de6f-11eb-90d3-7eaccd99ef23.png)

**Comment by pieckenst** [comment]
Ah it seems i forgot to update main.py there

**Comment by pieckenst** [comment]
One moment

**Comment by pieckenst** [comment]
look.launch_time = datetime.datetime.utcnow()
        hmm strange this line is present in the code

**Comment by pieckenst** [comment]
Replace look.launch_time = datetime.datetime.utcnow() with self.launch_time = datetime.datetime.utcnow()

**Comment by pieckenst** [comment]
That should fix it for ya

**Comment by pieckenst** [comment]
@ojomangame

**Comment by Rocky-pup** [comment]
thanks
